include Makefile.common

all:
	$(MAKE) -C util
	$(MAKE) -C lexer
	$(MAKE) -C parser
	$(MAKE) -C rex

clean:
	$(MAKE) -C util clean
	$(MAKE) -C lexer clean
	$(MAKE) -C parser clean
	$(MAKE) -C rex clean
