include Makefile.common

all:
	$(MAKE) -C ast
	$(MAKE) -C cmlexer
	$(MAKE) -C cmnothrowlexer
	$(MAKE) -C cmparser
	$(MAKE) -C cmnothrowparser

clean:
	$(MAKE) -C ast clean
	$(MAKE) -C cmlexer clean
	$(MAKE) -C cmnothrowlexer clean
	$(MAKE) -C cmparser clean
	$(MAKE) -C cmnothrowparser
