CXX=clang++
CC=clang
AR=llvm-ar
ifeq ($(config),debug)
CXXFLAGS += -pthread -fPIC -std=c++14 -I../.. -I../../.. -g -O0
CFLAGS += -pthread -fPIC -I../.. -g -O0
else
CXXFLAGS += -pthread -fPIC -std=c++14 -I../.. -I../../.. -DNDEBUG -g -O3
CFLAGS += -pthread -fPIC -I../.. -DNDEBUG -g -O3
endif
