CXX=clang++
CC=clang
AR=llvm-ar
ifeq ($(config),debug)
CXXFLAGS += -pthread -fPIC -std=c++20 -I../.. -I.. -L../lib -g -O0
CFLAGS += -pthread -fPIC -I../.. -g -O0
else
CXXFLAGS += -pthread -fPIC -std=c++20 -I../.. -I.. -L../lib -DNDEBUG -O3
CFLAGS += -pthread -fPIC -I../.. -DNDEBUG -O3
endif
