include Makefile.common

all:
	$(MAKE) -C dom
	$(MAKE) -C xml
	$(MAKE) -C xpath
	$(MAKE) -C serialization
	$(MAKE) -C xmlsergen

clean:
	$(MAKE) -C dom clean
	$(MAKE) -C xml clean
	$(MAKE) -C xpath clean
	$(MAKE) -C serialization clean
	$(MAKE) -C xmlsergen clean
