project code;
reference <../parsing/StdLib.pl>;
source <Declaration.parser>;
source <Declarator.parser>;
source <Expression.parser>;
source <Identifier.parser>;
source <Keyword.parser>;
source <Literal.parser>;
source <Statement.parser>;
