@echo off
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmct.exe ..\bin
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmbst.exe ..\bin
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmbs_tracet.dll ..\bin
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmbs_tracet.lib ..\lib
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmbs_trace_initt.exe ..\bin
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmclientt.exe ..\bin
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmservert.exe ..\bin
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmdbt.exe ..\bin
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmdb2xmlt.exe ..\bin
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmtracet.dll ..\bin
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmtracet.lib ..\lib
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmtrace2txtt.exe ..\bin
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmtrace2xmlt.exe ..\bin
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmpmt.dll ..\bin
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmpmt.lib ..\lib
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmpmst.exe ..\bin
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmupdt.exe ..\bin
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmdebugt.dll ..\bin
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmdebugt.lib ..\lib
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmsngcmastt.dll ..\bin
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmsngcmastt.lib ..\lib
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmsnglexert.dll ..\bin
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmsnglexert.lib ..\lib
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmsngparsert.dll ..\bin
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmsngparsert.lib ..\lib
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmsngcmlexert.dll ..\bin
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmsngcmlexert.lib ..\lib
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmsngcmparsert.dll ..\bin
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmsngcmparsert.lib ..\lib
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmsngxmlxmlt.dll ..\bin
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmsngxmlxmlt.lib ..\lib
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmsngxmldomt.dll ..\bin
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmsngxmldomt.lib ..\lib
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmsngxmlsert.dll ..\bin
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmsngxmlsert.lib ..\lib
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\xmlsergent.exe ..\bin
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmsngxmlxpatht.dll ..\bin
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmsngxmlxpatht.lib ..\lib
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\bindert.dll ..\bin
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\bindert.lib ..\lib
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\buildt.dll ..\bin
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\buildt.lib ..\lib
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmllvmt.dll ..\bin
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmllvmt.lib ..\lib
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmsxbet.dll ..\bin
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmsxbet.lib ..\lib
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmsxit.dll ..\bin
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmsxit.lib ..\lib
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmmidt.dll ..\bin
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmmidt.lib ..\lib
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\codegent.dll ..\bin
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\codegent.lib ..\lib
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\codegenbaset.dll ..\bin
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\codegenbaset.lib ..\lib
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\codegenllvmt.dll ..\bin
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\codegenllvmt.lib ..\lib
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\codegenwint.dll ..\bin
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\codegenwint.lib ..\lib
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\codegensxt.dll ..\bin
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\codegensxt.lib ..\lib
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmsngjsont.dll ..\bin
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmsngjsont.lib ..\lib
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmcppit.dll ..\bin
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmcppit.lib ..\lib
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmcppbet.dll ..\bin
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmcppbet.lib ..\lib
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\codegencppt.dll ..\bin
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\codegencppt.lib ..\lib
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cppcmct.exe ..\bin
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cppcmcconfigt.exe ..\bin
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmtoolchaint.dll ..\bin
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmtoolchaint.lib ..\lib
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmtoolchainconfigt.exe ..\bin
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmvcxprojectfilegent.exe ..\bin
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmslnfilegent.exe ..\bin
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\irt.dll ..\bin
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\irt.lib ..\lib
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\symbolst.dll ..\bin
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\symbolst.lib ..\lib
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmrest.dll ..\bin
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmrest.lib ..\lib
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmsngrext.dll ..\bin
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmsngrext.lib ..\lib
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmsngutilt.dll ..\bin
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmsngutilt.lib ..\lib
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmcmt.dll ..\bin
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmcmt.lib ..\lib
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmrt390t.dll ..\bin
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmrt390t.lib ..\lib
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmrtst.lib ..\lib\vs
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\eht.lib ..\lib\vs
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cm2htmlt.exe ..\bin
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmdoct.exe ..\bin
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmdoclibt.dll ..\bin
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmdoclibt.lib ..\lib
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmfileredirectort.exe ..\bin
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmmdumpt.exe ..\bin
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmp2cmprojt.exe ..\bin
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmproj2cmpt.exe ..\bin
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmproft.exe ..\bin
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\sxcmct.exe ..\bin
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cms2slnt.exe ..\bin
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cmunitt.exe ..\bin
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\makecmajorucdt.exe ..\bin
xcopy /Y /D C:\work\cmajorm\cmajor\x64\Trace\cppcmparsert.exe ..\bin
