@echo off
del ..\bin\cmct.exe
del ..\bin\cmbst.exe
del ..\bin\cmbs_tracet.dll
del ..\lib\cmbs_tracet.lib
del ..\bin\cmbs_trace_init.exe
del ..\bin\cmclientt.exe
del ..\bin\cmservert.exe
del ..\bin\cmdbt.exe
del ..\bin\cmdb2xmlt.exe
del ..\bin\cmtracet.dll
del ..\lib\cmtracet.lib
del ..\bin\cmtrace2txtt.exe
del ..\bin\cmtrace2xmlt.exe
del ..\bin\cmpmt.dll
del ..\lib\cmpmt.lib
del ..\bin\cmpmst.exe
del ..\bin\cmupdt.exe
del ..\bin\cmdebugt.dll
del ..\lib\cmdebugt.lib
del ..\bin\cmsngcmastt.dll
del ..\lib\cmsngcmastt.lib
del ..\bin\cmsnglexert.dll
del ..\lib\cmsnglexert.lib
del ..\bin\cmsngparsert.dll
del ..\lib\cmsngparsert.lib
del ..\bin\cmsngcmlexert.dll
del ..\lib\cmsngcmlexert.lib
del ..\bin\cmsngcmparsert.dll
del ..\lib\cmsngcmparsert.lib
del ..\bin\cmsngxmlxmlt.dll
del ..\lib\cmsngxmlxmlt.lib
del ..\bin\cmsngxmldomt.dll
del ..\lib\cmsngxmldomt.lib
del ..\bin\cmsngxmlsert.dll
del ..\lib\cmsngxmlsert.lib
del ..\bin\xmlsergent.exe
del ..\bin\cmsngxmlxpatht.dll
del ..\lib\cmsngxmlxpatht.lib
del ..\bin\bindert.dll
del ..\lib\bindert.lib
del ..\bin\buildt.dll
del ..\lib\buildt.lib
del ..\bin\cmllvmt.dll
del ..\lib\cmllvmt.lib
del ..\bin\cmsxbet.dll
del ..\lib\cmsxbet.lib
del ..\bin\cmsxit.dll
del ..\lib\cmsxit.lib
del ..\bin\cmmidt.dll
del ..\lib\cmmidt.lib
del ..\bin\codegent.dll
del ..\lib\codegent.lib
del ..\bin\codegenbaset.dll
del ..\lib\codegenbaset.lib
del ..\bin\codegenllvmt.dll
del ..\lib\codegenllvmt.lib
del ..\bin\codegenwint.dll
del ..\lib\codegenwint.lib
del ..\bin\codegensxt.dll
del ..\lib\codegensxt.lib
del ..\bin\cmsngjsont.dll
del ..\lib\cmsngjsont.lib
del ..\bin\cmcppit.dll
del ..\lib\cmcppit.lib
del ..\bin\cmcppbet.dll
del ..\lib\cmcppbet.lib
del ..\bin\codegencppt.dll
del ..\lib\codegencppt.lib
del ..\bin\cppcmct.exe
del ..\bin\cppcmcconfigt.exe
del ..\bin\cmtoolchaint.dll
del ..\lib\cmtoolchaint.lib
del ..\bin\cmtoolchainconfigt.exe
del ..\bin\cmvcxprojectfilegent.exe
del ..\bin\cmslnfilegent.exe
del ..\bin\irt.dll
del ..\lib\irt.lib
del ..\bin\symbolst.dll
del ..\lib\symbolst.lib
del ..\bin\cmrest.dll
del ..\lib\cmrest.lib
del ..\bin\cmsngrext.dll
del ..\lib\cmsngrext.lib
del ..\bin\cmsngutilt.dll
del ..\lib\cmsngutilt.lib
del ..\bin\cmcmt.dll
del ..\lib\cmcmt.lib
del ..\bin\cmrt390t.dll
del ..\lib\cmrt390t.lib
del ..\lib\cmrtst.lib
del ..\lib\eht.lib
del ..\bin\cm2htmlt.exe
del ..\bin\cmdoct.exe
del ..\bin\cmdoclibt.dll
del ..\lib\cmdoclibt.lib
del ..\bin\cmfileredirectort.exe
del ..\bin\cmmdumpt.exe
del ..\bin\cmp2cmprojt.exe
del ..\bin\cmproj2cmpt.exe
del ..\bin\cmproft.exe
del ..\bin\sxcmct.exe
del ..\bin\cms2slnt.exe
del ..\bin\cmunitt.exe
del ..\bin\makecmajorucdt.exe
del ..\bin\cppcmparsert.exe
