@echo off
if NOT EXIST ..\bin md ..\bin
if NOT EXIST ..\..\bin md ..\..\bin
cminst -v coreutil\cat\bin\debug\cat.x ..\..\bin\catd.x
cminst -v coreutil\cat\bin\release\cat.x ..\..\bin\cat.x
cminst -v coreutil\chmod\bin\debug\chmod.x ..\..\bin\chmodd.x
cminst -v coreutil\chmod\bin\release\chmod.x ..\..\bin\chmod.x
cminst -v coreutil\cp\bin\debug\cp.x ..\..\bin\cpd.x
cminst -v coreutil\cp\bin\release\cp.x ..\..\bin\cp.x
cminst -v coreutil\echo\bin\debug\echo.x ..\..\bin\echod.x
cminst -v coreutil\echo\bin\release\echo.x ..\..\bin\echo.x
cminst -v coreutil\head\bin\debug\head.x ..\..\bin\headd.x
cminst -v coreutil\head\bin\release\head.x ..\..\bin\head.x
cminst -v coreutil\hexdump\bin\debug\hexdump.x ..\..\bin\hexdumpd.x
cminst -v coreutil\hexdump\bin\release\hexdump.x ..\..\bin\hexdump.x
cminst -v coreutil\kill\bin\debug\kill.x ..\..\bin\killd.x
cminst -v coreutil\kill\bin\release\kill.x ..\..\bin\kill.x
cminst -v coreutil\less\bin\debug\less.x ..\..\bin\lessd.x
cminst -v coreutil\less\bin\release\less.x ..\..\bin\less.x
cminst -v coreutil\login\bin\debug\login.x ..\..\bin\logind.x
cminst -v coreutil\login\bin\release\login.x ..\..\bin\login.x
cminst -v coreutil\ls\bin\debug\ls.x ..\..\bin\lsd.x
cminst -v coreutil\ls\bin\release\ls.x ..\..\bin\ls.x
cminst -v coreutil\mkdir\bin\debug\mkdir.x ..\..\bin\mkdird.x
cminst -v coreutil\mkdir\bin\release\mkdir.x ..\..\bin\mkdir.x
cminst -v coreutil\mv\bin\debug\mv.x ..\..\bin\mvd.x
cminst -v coreutil\mv\bin\release\mv.x ..\..\bin\mv.x
cminst -v coreutil\passwd\bin\debug\passwd.x ..\..\bin\passwdd.x
cminst -v coreutil\passwd\bin\release\passwd.x ..\..\bin\passwd.x
cminst -v coreutil\rm\bin\debug\rm.x ..\..\bin\rmd.x
cminst -v coreutil\rm\bin\release\rm.x ..\..\bin\rm.x
cminst -v coreutil\rmdir\bin\debug\rmdir.x ..\..\bin\rmdird.x
cminst -v coreutil\rmdir\bin\release\rmdir.x ..\..\bin\rmdir.x
cminst -v coreutil\sudo\bin\debug\sudo.x ..\..\bin\sudod.x
cminst -v coreutil\sudo\bin\release\sudo.x ..\..\bin\sudo.x
cminst -v coreutil\time\bin\debug\time.x ..\..\bin\timed.x
cminst -v coreutil\time\bin\release\time.x ..\..\bin\time.x
cminst -v coreutil\tail\bin\debug\tail.x ..\..\bin\taild.x
cminst -v coreutil\tail\bin\release\tail.x ..\..\bin\tail.x
cminst -v coreutil\whoami\bin\debug\whoami.x ..\..\bin\whoamid.x
cminst -v coreutil\whoami\bin\release\whoami.x ..\..\bin\whoami.x
cminst -v editor\bin\debug\e.x ..\..\bin\ed.x
cminst -v editor\bin\release\e.x ..\..\bin\e.x
cminst -v shell\bin\debug\sh.x ..\..\bin\shd.x
cminst -v shell\bin\release\sh.x ..\..\bin\sh.x
cminst -v tab\bin\debug\tab.x ..\..\bin\tabd.x
cminst -v tab\bin\release\tab.x ..\..\bin\tab.x
cminst -v sx\bin\debug\sx.x ..\..\bin\sxd.x
cminst -v sx\bin\release\sx.x ..\..\bin\sx.x
